development:
  secret_key_base: 7f0f57ca4bb72ad3c5d9ffdd4ab8d886617f6db73631e7f5a482bb6080b88012e36b1f5928586711aad0aeb92f329fc62d3d5caf615aa04ab59124da6d84b4b6
  aws_access_key_id: <%= ENV["AWS_ACCES_KEY_ID"] %>
  aws_secrets_access_key: <%= ENV["AWS_SECRETS_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>

test:
  secret_key_base: aeed652a4af16c7876345c92251e6009ebcaea18d64aa339345049147d56f6eaf731657304d2fc7de6c19813ef0afc8a78ef57c5dbad6e9f34a01909c2482c88
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCES_KEY_ID"] %>
  aws_secrets_access_key: <%= ENV["AWS_SECRETS_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_key: <%= ENV["PRODUCTION_TWITTER_KEY"] %>
  twitter_secret: <%= ENV["PRODUCTION_TWITTER_SECRET"] %>
